Repository makeopensource/devU-api, pull requests merged in 2022-10, with the labels that each got.

#14 Added Submission Problem Score Model
  src/migration/1665020208581-addSubmissionProblemScores.ts
  src/model/index.ts
  src/model/submissionProblemScores.model.ts
Labels: hacktoberfest-accepted

#16 [Dependencies] Update deps to resolve vulns
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#17 added SubmissionProblemScore router
  package-lock.json
  package.json
  src/router/submissionProblemScores.router.ts
Labels: enhancement, hacktoberfest-accepted

#19 [Documentation] Fix project referred to as example
  README.md
  package.json
Labels: hacktoberfest-accepted

#23 [GitHub Actions] Set up GitHub Actions to automatically build, test, and format
  .github/workflows/pr-review.yml
  docs/SCHEMA.md
  docs/localAuth.md
  docs/postman-setup.md
  src/controller/tests/userCourses.controller.test.ts
  src/controller/userCourses.controller.ts
Labels: enhancement
